'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class BaseDeDatosProyectoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BaseDeDatosProyectoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categoria_Producto() As DbSet(Of Categoria_Producto)
    Public Overridable Property Clientes() As DbSet(Of Clientes)
    Public Overridable Property Detalle_Factura() As DbSet(Of Detalle_Factura)
    Public Overridable Property Empleados() As DbSet(Of Empleados)
    Public Overridable Property Facturas() As DbSet(Of Facturas)
    Public Overridable Property Productos() As DbSet(Of Productos)
    Public Overridable Property Tipo_Usuario() As DbSet(Of Tipo_Usuario)

    <DbFunction("BaseDeDatosProyectoEntities", "obtenerProductosVendidosCategoria")>
    Public Overridable Function obtenerProductosVendidosCategoria(fecha_desde As String, fecha_hasta As String) As IQueryable(Of obtenerProductosVendidosCategoria_Result)
        Dim fecha_desdeParameter As ObjectParameter = If(fecha_desde IsNot Nothing, New ObjectParameter("fecha_desde", fecha_desde), New ObjectParameter("fecha_desde", GetType(String)))

        Dim fecha_hastaParameter As ObjectParameter = If(fecha_hasta IsNot Nothing, New ObjectParameter("fecha_hasta", fecha_hasta), New ObjectParameter("fecha_hasta", GetType(String)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of obtenerProductosVendidosCategoria_Result)("[BaseDeDatosProyectoEntities].[obtenerProductosVendidosCategoria](@fecha_desde, @fecha_hasta)", fecha_desdeParameter, fecha_hastaParameter)
    End Function

    <DbFunction("BaseDeDatosProyectoEntities", "obtenerProductosVendidosNombre")>
    Public Overridable Function obtenerProductosVendidosNombre(fecha_desde As String, fecha_hasta As String) As IQueryable(Of obtenerProductosVendidosNombre_Result)
        Dim fecha_desdeParameter As ObjectParameter = If(fecha_desde IsNot Nothing, New ObjectParameter("fecha_desde", fecha_desde), New ObjectParameter("fecha_desde", GetType(String)))

        Dim fecha_hastaParameter As ObjectParameter = If(fecha_hasta IsNot Nothing, New ObjectParameter("fecha_hasta", fecha_hasta), New ObjectParameter("fecha_hasta", GetType(String)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of obtenerProductosVendidosNombre_Result)("[BaseDeDatosProyectoEntities].[obtenerProductosVendidosNombre](@fecha_desde, @fecha_hasta)", fecha_desdeParameter, fecha_hastaParameter)
    End Function

    <DbFunction("BaseDeDatosProyectoEntities", "obtenerProductosVendidosVendedor")>
    Public Overridable Function obtenerProductosVendidosVendedor(fecha_desde As String, fecha_hasta As String) As IQueryable(Of obtenerProductosVendidosVendedor_Result)
        Dim fecha_desdeParameter As ObjectParameter = If(fecha_desde IsNot Nothing, New ObjectParameter("fecha_desde", fecha_desde), New ObjectParameter("fecha_desde", GetType(String)))

        Dim fecha_hastaParameter As ObjectParameter = If(fecha_hasta IsNot Nothing, New ObjectParameter("fecha_hasta", fecha_hasta), New ObjectParameter("fecha_hasta", GetType(String)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of obtenerProductosVendidosVendedor_Result)("[BaseDeDatosProyectoEntities].[obtenerProductosVendidosVendedor](@fecha_desde, @fecha_hasta)", fecha_desdeParameter, fecha_hastaParameter)
    End Function

End Class
