'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property id_cliente As Integer
    Public Property nombre As String
    Public Property dni As Integer

    Public Overridable Property Facturas As ICollection(Of Facturas) = New HashSet(Of Facturas)

End Class
