'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Detalle_Factura
    Public Property id_detalle As Integer
    Public Property id_factura As Integer
    Public Property id_producto As Integer
    Public Property cantidad As Integer
    Public Property precio_detalle As Double

    Public Overridable Property Facturas As Facturas
    Public Overridable Property Productos As Productos

End Class
