'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property id_empleado As Integer
    Public Property id_tipo As Integer
    Public Property dni As String
    Public Property nombre As String
    Public Property apellido As String
    Public Property nombre_usuario As String
    Public Property contraseña As String
    Public Property habilitado As String

    Public Overridable Property Tipo_Usuario As Tipo_Usuario
    Public Overridable Property Facturas As ICollection(Of Facturas) = New HashSet(Of Facturas)

End Class
