'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Facturas
    Public Property id_factura As Integer
    Public Property id_cliente As Integer
    Public Property id_empleado As Integer
    Public Property fecha As String
    Public Property hora As String
    Public Property precio_total As Double

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Detalle_Factura As ICollection(Of Detalle_Factura) = New HashSet(Of Detalle_Factura)
    Public Overridable Property Empleados As Empleados

End Class
