'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Productos
    Public Property id_producto As Integer
    Public Property id_categoria As Integer
    Public Property nombre As String
    Public Property stock As Integer
    Public Property stock_min As Integer
    Public Property precio As Double
    Public Property habilitado As String

    Public Overridable Property Categoria_Producto As Categoria_Producto
    Public Overridable Property Detalle_Factura As ICollection(Of Detalle_Factura) = New HashSet(Of Detalle_Factura)

End Class
